
%-----------------------------------------------------------------%
max_frequ = max(max(indegree_frequ));
new_ind5 = indegree_frequ(1,:)./max_frequ;
new_ind6 = indegree_frequ(2,:)./max_frequ;
new_ind7 = indegree_frequ(3,:)./max_frequ;
new_ind8 = indegree_frequ(4,:)./max_frequ;
new_ind9 = indegree_frequ(5,:)./max_frequ;
new_ind10 = indegree_frequ(6,:)./max_frequ;
new_ind11 = indegree_frequ(7,:)./max_frequ;
new_ind12 = indegree_frequ(8,:)./max_frequ;
new_ind13 = indegree_frequ(9,:)./max_frequ;
new_ind14 = indegree_frequ(10,:)./max_frequ;
new_ind15 = indegree_frequ(11,:)./max_frequ;
new_ind16 = indegree_frequ(12,:)./max_frequ;
new_ind17 = indegree_frequ(13,:)./max_frequ;
new_ind18 = indegree_frequ(14,:)./max_frequ;
new_ind19 = indegree_frequ(15,:)./max_frequ;
new_ind20 = indegree_frequ(16,:)./max_frequ;

hold on;
plot(indegree_eleme(1,:)+1,new_ind5,...
    'MarkerSize',5,'Marker','*','Color',[0 0 0],...
    'DisplayName','n = 5');
plot(indegree_eleme(2,:)+1,new_ind6,...
    'MarkerSize',5,'Marker','o','Color',[1 0 0],...
    'DisplayName','n = 6');
plot(indegree_eleme(3,:)+1,new_ind7,...
    'MarkerSize',5,'Marker','v','Color',[0 1 0],...
    'DisplayName','n = 7');
plot(indegree_eleme(4,:)+1,new_ind8,...
    'MarkerSize',5,'Marker','^','Color',[0 0 1],...
    'DisplayName','n = 8');
plot(indegree_eleme(5,:)+1,new_ind9,...
    'MarkerSize',5,'Marker','p','Color',[1 0 1],...
    'DisplayName','n = 9');
plot(indegree_eleme(6,:)+1,new_ind10,...
    'MarkerSize',5,'Marker','h','Color',[0 1 1],...
    'DisplayName','n = 10');
plot(indegree_eleme(7,:)+1,new_ind11,...
    'MarkerSize',5,'Marker','d','Color',[0.667 0.667 1],...
    'DisplayName','n = 11');
plot(indegree_eleme(8,:)+1,new_ind12,...
    'MarkerSize',5,'Marker','s','Color',[0.5 0 0],...
    'DisplayName','n = 12');
plot(indegree_eleme(9,:)+1,new_ind13,...
    'MarkerSize',5,'Marker','*','Color',[0 0 0],...
    'DisplayName','n = 13');
plot(indegree_eleme(10,:)+1,new_ind14,...
    'MarkerSize',5,'Marker','o','Color',[1 0 0],...
    'DisplayName','n = 14');
plot(indegree_eleme(11,:)+1,new_ind15,...
    'MarkerSize',5,'Marker','v','Color',[0 1 0],...
    'DisplayName','n = 15');
plot(indegree_eleme(12,:)+1,new_ind16,...
    'MarkerSize',5,'Marker','^','Color',[0 0 1],...
    'DisplayName','n = 16');
plot(indegree_eleme(13,:)+1,new_ind17,...
    'MarkerSize',5,'Marker','p','Color',[1 0 1],...
    'DisplayName','n = 17');
plot(indegree_eleme(14,:)+1,new_ind18,...
    'MarkerSize',5,'Marker','h','Color',[0 1 1],...
    'DisplayName','n = 18');
plot(indegree_eleme(15,:)+1,new_ind19,...
    'MarkerSize',5,'Marker','d','Color',[0.667 0.667 1],...
    'DisplayName','n = 19');
plot(indegree_eleme(16,:)+1,new_ind20,...
    'MarkerSize',5,'Marker','s','Color',[0.5 0 0],...
    'DisplayName','n = 20');
legend('n = 5','n = 6','n = 7','n = 8',...
    'n = 9','n = 10','n = 11','n = 12',...
    'n = 13','n = 14','n = 15','n = 16',...
    'n = 17','n = 18','n = 19','n = 20',0);
xlabel('$k+1$','VerticalAlignment','top','Interpreter','latex','FontSize',14);
ylabel('$ratio$','Interpreter','latex','FontSize',14);


hold on;
k = [20:90];
len = length(k);
for i = 1:len
p(i) = 10*(16*(k(i)+1)/((121/32)^2*k(i)^2*(k(i)+2)^2));
end
plot(k,p);

figure1=gcf;

annotation(figure1,'textbox',...
    [0.36495180023229 0.323571831443498 0.213890969019972 0.0771428557804653],...
    'Interpreter','latex',...
    'String','$p(k)= \frac{16(k+1}{\mu^{2}k^{2}(k+2)^{2}}$',...
    'FontSize',14,...
    'FitBoxToText','on',...
    'EdgeColor',[1 1 1]);

% export_fig('new_InDegreeDistribution_u121_n_5_20.pdf','-transparent');
%-----------------------------------------------------------------%

