close all; clear all; clc;


load node_indegree_7bit.txt;
load node_indegree_8bit.txt;
load node_indegree_9bit.txt;
load node_indegree_10bit.txt;


hold on;
plot(node_indegree_7bit(:,1),node_indegree_7bit(:,2),...
    'MarkerSize',5,'Marker','v','Color',[0 1 0],...
    'DisplayName','n = 7');
plot(node_indegree_8bit(:,1),node_indegree_8bit(:,2),...
    'MarkerSize',5,'Marker','^','Color',[0 0 1],...
    'DisplayName','n = 8');
plot(node_indegree_9bit(:,1),node_indegree_9bit(:,2),...
    'MarkerSize',5,'Marker','p','Color',[1 0 1],...
    'DisplayName','n = 9');
plot(node_indegree_10bit(:,1),node_indegree_10bit(:,2),...
    'MarkerSize',5,'Marker','h','Color',[0 1 1],...
    'DisplayName','n = 10');

xlabel('$y$','Margin',2,'FontAngle','italic','FontSize',14,...
    'FontName','Times New Roman','interpreter', 'Latex');

ylabel('k','Margin',2,'FontAngle','italic','FontSize',14,...
    'FontName','Times New Roman');

% export_fig('y_k.pdf','-transparent');